### PR TITLE
Bulk Responses

### LINKED ISSUE #22: Add bulk response
We should have a `BulkResponse` that can be used to iterate over the outcome of operations.

I'm not totally sure what this should look like yet, since the response could look similar for non-success statuses. It's probably least surprising to return `Ok` for any non-exception response and have a convenience method for asserting all ops succeeded, or iterating over them manually.

### PR DESCRIPTION
**Pull request by KodrAus**
Closes #22 

Adds response types for the `_bulk` endpoint. There's a `BulkResponse` type that splits successful and failed operations and a `BulkErrorsResponse` type that only includes errors.

The idea is that once `serde 1.0` comes along with borrowed deserialisation we'll be able to avoid allocating any bulk response items if the user doesn't need them.

I'll add some more docs while I'm at it, and polish this up.

### CODE REVIEW

File: src/bulk.rs [hunk 1]
```diff
@@ -0,0 +1,331 @@
...
+/// Bulk items split by success or failure.
+#[derive(Debug, Clone)]
+pub struct BulkItems {
+    pub ok: Vec<BulkItem>,
+    pub err: Vec<BulkItemError>,
+}
+
+/// The bulk action being performed.
+#[derive(Debug, Clone)]
+pub enum BulkAction {
```
Comment (KodrAus) [inline src/bulk.rs]: Will `#[serde(rename = "index")]` etc work for these variants?

Comment (KodrAus) [reply src/bulk.rs]: It does work. Nice!

**Comment by KodrAus** [comment]
Gonna polish up the docs this evening then this should be good to go. I was a bit unsure about the `BulkItems` structure, but think it's ok as is so you can partially move things. In the future maybe we could look at deriving `Iterator<Item = Result<&BulkItem, &BulkItemError>>`.
